# Generated by Django 5.0.6 on 2024-06-07 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_delete_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
    ]
