# Generated by Django 5.0.6 on 2024-06-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("pick_up_date", models.DateField()),
                ("drop_off_date", models.DateField()),
                (
                    "car_model",
                    models.CharField(
                        choices=[
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Truck", "Truck"),
                            ("Convertible", "Convertible"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
