version: '3.8'

services:
  backend:
    build: 
      context: ./gym-backend/gym_app
      dockerfile: Dockerfile
    command: gunicorn gym_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./gym-backend/gym_app:/app
      - ./.venv:/app/.venv
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    build: 
      context: ./gym-frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./gym-frontend:/app
    ports:
      - "3000:3000"
