# Generated by Django 5.0.6 on 2024-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeproduct",
            name="image",
            field=models.ImageField(blank=True, upload_to="image"),
        ),
    ]
