# Generated by Django 5.0.6 on 2024-05-23 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_homeproduct_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homeproduct",
            old_name="name",
            new_name="Name",
        ),
    ]
