# Generated by Django 5.0.6 on 2024-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("author", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="images/")),
            ],
        ),
    ]
