# Generated by Django 5.0.6 on 2024-05-17 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="author",
        ),
        migrations.RemoveField(
            model_name="note",
            name="created_at",
        ),
    ]
