# Generated by Django 5.0.6 on 2024-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_note_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="completed",
        ),
    ]
